import re
from typing import Dict, List, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

class OutputStructurer:
    """Structure and format the final output from the model and other components"""

    def __init__(self):
        pass

    def parse_model_response(self, clinical_text: str, symptoms: str, icd_assigner) -> Dict:
        """
        Parse the clinical text generated by the model and assign ICD codes.
        
        Args:
            clinical_text: The text generated by the model
            symptoms: The patient's symptoms
            icd_assigner: Instance of ICD10CodeAssigner
            
        Returns:
            Dict containing parsed information and ICD codes
        """
        # Assign ICD-10 codes
        top_code, accuracy, keyword_matches = icd_assigner.assign_codes_with_accuracy(
            clinical_text, 
            symptoms
        )

        return {
            "clinical_note": clinical_text,
            "icd10_code": top_code,
            "confidence_score": accuracy,
            "reasoning": keyword_matches
        }

    def create_final_output(self, patient_json: Dict, model_output: Dict) -> Dict:
        """
        Combine patient data and model output into the final structure.
        
        Args:
            patient_json: Original patient data
            model_output: Output from parse_model_response
            
        Returns:
            Final structured dictionary
        """
        return {
            "patient_id": patient_json.get("PatientName", "Unknown"), # Using Name as ID for now if ID not present
            "timestamp": datetime.now().isoformat(),
            "patient_data": patient_json,
            "clinical_documentation": {
                "generated_note": model_output.get("clinical_note", ""),
                "icd_coding": {
                    "code": model_output.get("icd10_code", ""),
                    "description": self._get_icd_description(model_output.get("icd10_code", "")),
                    "confidence": model_output.get("confidence_score", 0.0),
                    "evidence": model_output.get("reasoning", {})
                }
            },
            "metadata": {
                "model_version": "1.0",
                "processing_time": datetime.now().isoformat() # Placeholder
            }
        }

    def _get_icd_description(self, code: str) -> str:
        """Helper to get description for a code (mock implementation)"""
        # In a real scenario, this would look up from the dataframe or database
        # For now, returning a generic description based on the code prefix or known codes
        descriptions = {
            'J18.9': 'Pneumonia, unspecified',
            'I10': 'Essential (primary) hypertension',
            'E11.9': 'Type 2 diabetes mellitus without complications',
            'M79.3': 'Panniculitis, unspecified', # Or similar
            'R50.9': 'Fever, unspecified',
            'R05.9': 'Cough, unspecified',
            'R11.0': 'Nausea',
            'R53.83': 'Other fatigue',
            'R51.9': 'Headache, unspecified',
            'R06.02': 'Shortness of breath',
            'R07.9': 'Chest pain, unspecified',
            'R10.9': 'Unspecified abdominal pain',
            'R42.0': 'Dizziness and giddiness',
            'R60.9': 'Edema, unspecified',
            'Z00.00': 'Encounter for general adult medical examination without abnormal findings'
        }
        return descriptions.get(code, "Description not found")
